[project]
name = "search-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "gensim>=4.3.3",
    "lxml>=6.0.1",
    "nltk>=3.9.1",
    "numpy>=1.26.4",
    "requests>=2.32.5",
]
